[book]
authors = ["Yandex Data School"]
language = "ru"
multilingual = false
src = "src"
title = "Курс Алгоритмов ШАД"

[output.html]
additional-css = ["assets/spoiler.css"]
mathjax-support = true
repository-url = "https://gitlab.com/ysda/algorithms"
